# Generated by Django 4.1.5 on 2023-05-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='user_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='userProfile.userprofile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='userProfile.userprofile'),
        ),
    ]
