# Generated by Django 4.1.5 on 2023-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_friend_friend_remove_friend_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
