# Generated by Django 4.1.5 on 2023-05-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
        ('friends', '0003_friend_status_delete_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True)),
                ('user_1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='userProfile.userprofile')),
                ('user_2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='userProfile.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
